fix broken incremental check build adds tests about check incremental build

diff --git a/tests/build b/tests/build
--- a/tests/build
+++ b/tests/build
@@ -85,6 +85,17 @@ cat ${l_dir}/reports/m1/check/tests.xml | grep -q tMyTest || {
   exit 1
 }
 
+
+# check check has incremental build
+l_mtime1=$(stat ${l_dir}/reports/m1/check/tests.xml | grep Modify | cut -d' ' -f2-3)
+touch ${l_srcdir}/m1/unit/TestCode.cc
+make check -j4
+l_mtime2=$(stat ${l_dir}/reports/m1/check/tests.xml | grep Modify | cut -d' ' -f2-3)
+if [ "${l_mtime1}" = "${l_mtime2}" ]; then
+    echo "error : check target is not incremental"
+    exit 1
+fi
+
 make  clean -j4  ${VERBOSE}
 if [ $? -ne 0 ]; then
     echo "error: failed to clean build tree"
